---
- hosts: localhost
  vars_files:
    - config.yml

  roles:
  - role: elliotweiser.osx-command-line-tools
  - role: geerlingguy.mac.homebrew
    tags: ['homebrew']
  - role: geerlingguy.mac.mas
    become: yes
    when: mas_installed_apps or mas_installed_app_ids
    tags: ['mas']
  - role: geerlingguy.mac.dock
    when: configure_dock
    tags: ['dock']

  tasks:
    - import_tasks: tasks/omz.yml
      tags: ['dotfiles']
    - import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']
    - import_tasks: tasks/pnpm.yml
      tags: ['pnpm']
    - import_tasks: tasks/nodejs.yml
      tags: ['nodejs']
    - import_tasks: tasks/deno.yml
      tags: ['deno']
    - import_tasks: tasks/rust.yml
      tags: ['rust']
    - import_tasks: tasks/configure-nvim.yml
      tags: ['nvim']
    - import_tasks: tasks/ensure-zsh-syntax-highlighting.yml
